--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : Apr 25 2017 12:03
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Person'   
-- id              :  
-- FirstName       :  
-- LastName        :  
-- City            :  
-- Street          :  
-- Num             :  
--
CREATE TABLE Person (
    id             NUMBER(38) NOT NULL,
    FirstName      CHAR(20) NOT NULL,
    LastName       CHAR(20) NOT NULL,
    City           CHAR(20) NOT NULL,
    Street         CHAR(20) NOT NULL,
    Num            NUMBER(38) NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY (id))
/


--
-- Create Table    : 'court'   
-- id              :  
-- Region          :  
-- Court_type      :  
--
CREATE TABLE court (
    id             NUMBER(38) NOT NULL,
    Region         CHAR(20) NOT NULL,
    Court_type     CHAR(20) NOT NULL,
CONSTRAINT pk_court PRIMARY KEY (id))
/


--
-- Create Table    : 'Defendant'   
-- id1             :  (references Person.id)
-- Id              :  
-- numPriors       :  
--
CREATE TABLE Defendant (
    id1            NUMBER(38) NOT NULL,
    Id             NUMBER(38) NOT NULL,
    numPriors      NUMBER(38) NOT NULL,
CONSTRAINT pk_Defendant PRIMARY KEY (id1,Id),
CONSTRAINT fk_Defendant FOREIGN KEY (id1)
    REFERENCES Person (id))
/


--
-- Create Table    : 'Lawer'   
-- id1             :  (references Person.id)
-- id              :  
-- StartDate       :  
-- Specializati    :  
--
CREATE TABLE Lawer (
    id1            NUMBER(38) NOT NULL,
    id             NUMBER(38) NOT NULL,
    StartDate      DATE NOT NULL,
    Specializati   CHAR(20) NOT NULL,
CONSTRAINT pk_Lawer PRIMARY KEY (id1,id),
CONSTRAINT fk_Lawer FOREIGN KEY (id1)
    REFERENCES Person (id))
/


--
-- Create Table    : 'Judge'   
-- id3             :  (references Person.id)
-- Id1             :  
-- StartDate       :  
-- id              :  
-- id2             :  (references court.id)
--
CREATE TABLE Judge (
    id3            NUMBER(38) NOT NULL,
    Id1            NUMBER(38) NOT NULL,
    StartDate      DATE NOT NULL,
    id             NUMBER(38) NOT NULL,
    id2            NUMBER(38) NOT NULL,
CONSTRAINT pk_Judge PRIMARY KEY (id3,Id1),
CONSTRAINT fk_Judge2 FOREIGN KEY (id3)
    REFERENCES Person (id),
CONSTRAINT fk_Judge FOREIGN KEY (id2)
    REFERENCES court (id)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'court_case'   
-- CaseId          :  
-- Case_type       :  
-- OpenDate        :  
-- CloseDate       :  
-- Verdict         :  
-- Id              :  
-- Id1             :  
-- id2             :  (references Lawer.id)
-- id3             :  (references Lawer.id)
-- id4             :  (references Defendant.id)
-- Id5             :  (references Defendant.Id)
--
CREATE TABLE court_case (
    CaseId         NUMBER(38) NOT NULL,
    Case_type      CHAR(20) NOT NULL,
    OpenDate       DATE NOT NULL,
    CloseDate      DATE NOT NULL,
    Verdict        CHAR(20) NOT NULL,
    Id             NUMBER(38) NOT NULL,
    Id1            NUMBER(38) NOT NULL,
    id2            NUMBER(38),
    id3            NUMBER(38),
    id4            NUMBER(38),
    Id5            NUMBER(38),
CONSTRAINT pk_court_case PRIMARY KEY (CaseId),
CONSTRAINT fk_court_case FOREIGN KEY (id2,id3)
    REFERENCES Lawer (id,id),
CONSTRAINT fk_court_case2 FOREIGN KEY (id4,Id5)
    REFERENCES Defendant (id,Id))
/


--
-- Create Table    : 'Appeal'   
-- Appld           :  
-- CaseId          :  
-- CaseId1         :  (references court_case.CaseId)
-- filingDate      :  
-- Verdict         :  
--
CREATE TABLE Appeal (
    Appld          CHAR(20) NOT NULL,
    CaseId         NUMBER(38) NOT NULL,
    CaseId1        NUMBER(38) NOT NULL,
    filingDate     DATE NOT NULL,
    Verdict        CHAR(20) NOT NULL,
CONSTRAINT pk_Appeal PRIMARY KEY (Appld,CaseId,CaseId1),
CONSTRAINT fk_Appeal FOREIGN KEY (CaseId1)
    REFERENCES court_case (Case_Id)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'Persides'   
-- id              :  (references Judge.id)
-- Id1             :  (references Judge.Id1)
-- CaseId          :  (references court_case.CaseId)
-- id2             :  
-- CaseId1         :  
--
CREATE TABLE Persides (
    id             NUMBER(38) NOT NULL,
    Id1            NUMBER(38) NOT NULL,
    CaseId         NUMBER(38) NOT NULL,
    id2            NUMBER(38) NOT NULL,
    CaseId1        NUMBER(38) NOT NULL,
CONSTRAINT pk_Persides PRIMARY KEY (id,Id1,CaseId,id2),
CONSTRAINT fk_Persides FOREIGN KEY (id,Id1)
    REFERENCES Judge (id,Id1)
    ON DELETE CASCADE,
CONSTRAINT fk_Persides2 FOREIGN KEY (CaseId)
    REFERENCES court_case (CaseId))
/


--
-- Permissions for: 'public'
--
GRANT ALL ON Person TO public
/
GRANT ALL ON court TO public
/
GRANT ALL ON Defendant TO public
/
GRANT ALL ON Lawer TO public
/
GRANT ALL ON Judge TO public
/
GRANT ALL ON court_case TO public
/
GRANT ALL ON Appeal TO public
/
GRANT ALL ON Persides TO public
/

exit;

