CREATE TABLE PERSON (
    P_Id           NUMBER(10) NOT NULL,
    First_Name     VARCHAR2(10) NOT NULL,
    Last_Name      VARCHAR2(10) NOT NULL,
    BirthDate      DATE NOT NULL,
    City           VARCHAR2(10) NOT NULL,
    Street         VARCHAR2(10) NOT NULL,
    H_Num          NUMBER NOT NULL,
CONSTRAINT pk_PERSON PRIMARY KEY (P_Id));


CREATE TABLE COURT (
    C_id           NUMBER(10) NOT NULL,
    C_Region       VARCHAR2(10) NOT NULL,
    Court_type     VARCHAR2(10) NOT NULL,
CONSTRAINT pk_COURT PRIMARY KEY (C_id));


CREATE TABLE DEFENDANT (
    P_Id           NUMBER(10) NOT NULL,
    NumPriors      NUMBER(10) NOT NULL,
CONSTRAINT pk_DEFENDANT PRIMARY KEY (P_Id),
CONSTRAINT fk_DEFENDANT FOREIGN KEY (P_Id)
    REFERENCES PERSON (P_Id));


CREATE TABLE LAWYER (
    P_Id           NUMBER(10) NOT NULL,
    StartDate      DATE NOT NULL,
    Specialization VARCHAR2(10) NOT NULL,
CONSTRAINT pk_LAWYER PRIMARY KEY (P_Id),
CONSTRAINT fk_LAWYER FOREIGN KEY (P_Id)
    REFERENCES PERSON (P_Id));


CREATE TABLE JUDGE (
    P_Id           NUMBER(10) NOT NULL,
    StartDate      DATE NOT NULL,
    C_id           NUMBER(10) NOT NULL,
CONSTRAINT pk_JUDGE PRIMARY KEY (P_Id),
CONSTRAINT fk_JUDGE2 FOREIGN KEY (P_Id)
    REFERENCES PERSON (P_Id),
CONSTRAINT fk_JUDGE FOREIGN KEY (C_id)
    REFERENCES COURT (C_id)
    ON DELETE CASCADE);


CREATE TABLE COURT_CASE (
    Case_Id        NUMBER(10) NOT NULL,
    Case_type      VARCHAR2(10) NOT NULL,
    OpenDate       DATE NOT NULL,
    CloseDate      DATE NOT NULL,
    Verdict        CHAR(1) NOT NULL,
    L_Id           NUMBER(10) NOT NULL,
    D_id           NUMBER(10) NOT NULL,
    P_Id           NUMBER(10),
    P_Id1          NUMBER(10),
CONSTRAINT pk_COURT_CASE PRIMARY KEY (Case_Id),
CONSTRAINT fk_COURT_CASE FOREIGN KEY (P_Id)
    REFERENCES LAWYER (P_Id),
CONSTRAINT fk_COURT_CASE2 FOREIGN KEY (P_Id1)
    REFERENCES DEFENDANT (P_Id));


CREATE TABLE APPEAL (
    App_Id         NUMBER(38) NOT NULL,
    Case_Id        NUMBER(10) NOT NULL,
    FilingDate     DATE NOT NULL,
    Verdict        CHAR(1) NOT NULL,
CONSTRAINT pk_APPEAL PRIMARY KEY (App_Id,Case_Id),
CONSTRAINT fk_APPEAL FOREIGN KEY (Case_Id)
    REFERENCES COURT_CASE (Case_Id)
    ON DELETE CASCADE);



CREATE TABLE PERSIDES (
    P_Id           NUMBER(10) NOT NULL,
    Case_Id        NUMBER(10) NOT NULL,
    J_Id           NUMBER(10) NOT NULL,
CONSTRAINT pk_PERSIDES PRIMARY KEY (P_Id,Case_Id,J_Id),
CONSTRAINT fk_PERSIDES FOREIGN KEY (P_Id)
    REFERENCES JUDGE (P_Id)
    ON DELETE CASCADE,
CONSTRAINT fk_PERSIDES2 FOREIGN KEY (Case_Id)
    REFERENCES COURT_CASE (Case_Id));


